name: Build Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build with Gradle
  run: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install gradle 8.8
    gradle build
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoPotionMod
        path: build/libs/*.jar
