name: Build Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: |
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew build
        else
          gradle wrapper --gradle-version=8.8
          chmod +x gradlew
          ./gradlew build
        fi
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoPotionMod
        path: build/libs/*.jar
